/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        canvas: '#0d0a08',
        card: '#1a1410',
        'card-hover': '#241c16',
        border: 'rgba(154, 144, 136, 0.2)',
        'border-muted': 'rgba(154, 144, 136, 0.12)',
        'border-accent': 'rgba(139, 58, 26, 0.4)',
        black: '#0a0806',
        forge: '#1a1410',
        iron: '#2c2420',
        ember: '#C4501A',
        brass: '#B8922A',
        rust: '#8B3A1A',
        ash: '#9a9088',
        bone: '#e8e0d4',
        paper: '#f2ece2',
        white: '#faf6f0',
        gain: '#5a9e6f',
        'gain-bright': '#8fc79e',
        'gain-tint': 'rgba(90, 158, 111, 0.1)',
        loss: '#b8412f',
        'loss-bright': '#e2765f',
        'loss-tint': 'rgba(184, 65, 47, 0.12)',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        serif: ['"Libre Baskerville"', 'Georgia', 'serif'],
        body: ['"Libre Baskerville"', 'Georgia', 'serif'],
        ui: ['"Barlow Condensed"', 'sans-serif'],
        mono: ['"Geist Mono"', '"JetBrains Mono"', 'monospace'],
        sans: ['"Barlow Condensed"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0px',
        none: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        full: '0px',
      },
    },
  },
  plugins: [],
};

